enum WindowsKey {
  // Mouse Buttons
  WINDOWS_KEY_LBUTTON = 0x01,   // Left mouse button
  WINDOWS_KEY_RBUTTON = 0x02,   // Right mouse button
  WINDOWS_KEY_CANCEL = 0x03,    // Control-break processing
  WINDOWS_KEY_MBUTTON = 0x04,   // Middle mouse button (three-button mouse)
  WINDOWS_KEY_XBUTTON1 = 0x05,  // X1 mouse button
  WINDOWS_KEY_XBUTTON2 = 0x06,  // X2 mouse button

  // Keyboard - Control Keys
  WINDOWS_KEY_BACK = 0x08,     // BACKSPACE key
  WINDOWS_KEY_TAB = 0x09,      // TAB key
  WINDOWS_KEY_CLEAR = 0x0C,    // CLEAR key
  WINDOWS_KEY_RETURN = 0x0D,   // ENTER key
  WINDOWS_KEY_SHIFT = 0x10,    // SHIFT key
  WINDOWS_KEY_CONTROL = 0x11,  // CTRL key
  WINDOWS_KEY_MENU = 0x12,     // ALT key
  WINDOWS_KEY_PAUSE = 0x13,    // PAUSE key
  WINDOWS_KEY_CAPITAL = 0x14,  // CAPS LOCK key
  WINDOWS_KEY_ESCAPE = 0x1B,   // ESC key
  WINDOWS_KEY_SPACE = 0x20,    // SPACEBAR
  WINDOWS_KEY_PRIOR = 0x21,    // PAGE UP key
  WINDOWS_KEY_NEXT = 0x22,     // PAGE DOWN key
  WINDOWS_KEY_END = 0x23,      // END key
  WINDOWS_KEY_HOME = 0x24,     // HOME key
  WINDOWS_KEY_LEFT = 0x25,     // LEFT ARROW key
  WINDOWS_KEY_UP = 0x26,       // UP ARROW key
  WINDOWS_KEY_RIGHT = 0x27,    // RIGHT ARROW key
  WINDOWS_KEY_DOWN = 0x28,     // DOWN ARROW key
  WINDOWS_KEY_SELECT = 0x29,
  WINDOWS_KEY_PRINT = 0x2A,
  WINDOWS_KEY_EXECUTE = 0x2B,
  WINDOWS_KEY_SNAPSHOT = 0x2C,  // PRINT SCREEN key
  WINDOWS_KEY_INSERT = 0x2D,    // INS key
  WINDOWS_KEY_DELETE = 0x2E,    // DEL key
  WINDOWS_KEY_HELP = 0x2F,

  // Number Keys
  WINDOWS_KEY_0 = 0x30,
  WINDOWS_KEY_1 = 0x31,
  WINDOWS_KEY_2 = 0x32,
  WINDOWS_KEY_3 = 0x33,
  WINDOWS_KEY_4 = 0x34,
  WINDOWS_KEY_5 = 0x35,
  WINDOWS_KEY_6 = 0x36,
  WINDOWS_KEY_7 = 0x37,
  WINDOWS_KEY_8 = 0x38,
  WINDOWS_KEY_9 = 0x39,

  // Alphabet Keys
  WINDOWS_KEY_A = 0x41,
  WINDOWS_KEY_B = 0x42,
  WINDOWS_KEY_C = 0x43,
  WINDOWS_KEY_D = 0x44,
  WINDOWS_KEY_E = 0x45,
  WINDOWS_KEY_F = 0x46,
  WINDOWS_KEY_G = 0x47,
  WINDOWS_KEY_H = 0x48,
  WINDOWS_KEY_I = 0x49,
  WINDOWS_KEY_J = 0x4A,
  WINDOWS_KEY_K = 0x4B,
  WINDOWS_KEY_L = 0x4C,
  WINDOWS_KEY_M = 0x4D,
  WINDOWS_KEY_N = 0x4E,
  WINDOWS_KEY_O = 0x4F,
  WINDOWS_KEY_P = 0x50,
  WINDOWS_KEY_Q = 0x51,
  WINDOWS_KEY_R = 0x52,
  WINDOWS_KEY_S = 0x53,
  WINDOWS_KEY_T = 0x54,
  WINDOWS_KEY_U = 0x55,
  WINDOWS_KEY_V = 0x56,
  WINDOWS_KEY_W = 0x57,
  WINDOWS_KEY_X = 0x58,
  WINDOWS_KEY_Y = 0x59,
  WINDOWS_KEY_Z = 0x5A,

  // Function Keys
  WINDOWS_KEY_F1 = 0x70,
  WINDOWS_KEY_F2 = 0x71,
  WINDOWS_KEY_F3 = 0x72,
  WINDOWS_KEY_F4 = 0x73,
  WINDOWS_KEY_F5 = 0x74,
  WINDOWS_KEY_F6 = 0x75,
  WINDOWS_KEY_F7 = 0x76,
  WINDOWS_KEY_F8 = 0x77,
  WINDOWS_KEY_F9 = 0x78,
  WINDOWS_KEY_F10 = 0x79,
  WINDOWS_KEY_F11 = 0x7A,
  WINDOWS_KEY_F12 = 0x7B,
  WINDOWS_KEY_F13 = 0x7C,
  WINDOWS_KEY_F14 = 0x7D,
  WINDOWS_KEY_F15 = 0x7E,
  WINDOWS_KEY_F16 = 0x7F,
  WINDOWS_KEY_F17 = 0x80,
  WINDOWS_KEY_F18 = 0x81,
  WINDOWS_KEY_F19 = 0x82,
  WINDOWS_KEY_F20 = 0x83,
  WINDOWS_KEY_F21 = 0x84,
  WINDOWS_KEY_F22 = 0x85,
  WINDOWS_KEY_F23 = 0x86,
  WINDOWS_KEY_F24 = 0x87,

  // Numpad Keys
  WINDOWS_KEY_NUMLOCK = 0x90,
  WINDOWS_KEY_SCROLL = 0x91,
  WINDOWS_KEY_NUMPAD0 = 0x60,
  WINDOWS_KEY_NUMPAD1 = 0x61,
  WINDOWS_KEY_NUMPAD2 = 0x62,
  WINDOWS_KEY_NUMPAD3 = 0x63,
  WINDOWS_KEY_NUMPAD4 = 0x64,
  WINDOWS_KEY_NUMPAD5 = 0x65,
  WINDOWS_KEY_NUMPAD6 = 0x66,
  WINDOWS_KEY_NUMPAD7 = 0x67,
  WINDOWS_KEY_NUMPAD8 = 0x68,
  WINDOWS_KEY_NUMPAD9 = 0x69,
  WINDOWS_KEY_MULTIPLY = 0x6A,
  WINDOWS_KEY_ADD = 0x6B,
  WINDOWS_KEY_SEPARATOR = 0x6C,
  WINDOWS_KEY_SUBTRACT = 0x6D,
  WINDOWS_KEY_DECIMAL = 0x6E,
  WINDOWS_KEY_DIVIDE = 0x6F,

  // System Keys
  WINDOWS_KEY_LSHIFT = 0xA0,
  WINDOWS_KEY_RSHIFT = 0xA1,
  WINDOWS_KEY_LCONTROL = 0xA2,
  WINDOWS_KEY_RCONTROL = 0xA3,
  WINDOWS_KEY_LMENU = 0xA4,  // Left ALT
  WINDOWS_KEY_RMENU = 0xA5,  // Right ALT
  WINDOWS_KEY_LWIN = 0x5B,   // Left Windows key
  WINDOWS_KEY_RWIN = 0x5C,   // Right Windows key
  WINDOWS_KEY_APPS = 0x5D,   // Applications key (Menu key)

  // Browser and Media Keys
  WINDOWS_KEY_BROWSER_BACK = 0xA6,
  WINDOWS_KEY_BROWSER_FORWARD = 0xA7,
  WINDOWS_KEY_BROWSER_REFRESH = 0xA8,
  WINDOWS_KEY_BROWSER_STOP = 0xA9,
  WINDOWS_KEY_BROWSER_SEARCH = 0xAA,
  WINDOWS_KEY_BROWSER_FAVORITES = 0xAB,
  WINDOWS_KEY_BROWSER_HOME = 0xAC,
  WINDOWS_KEY_VOLUME_MUTE = 0xAD,
  WINDOWS_KEY_VOLUME_DOWN = 0xAE,
  WINDOWS_KEY_VOLUME_UP = 0xAF,
  WINDOWS_KEY_MEDIA_NEXT_TRACK = 0xB0,
  WINDOWS_KEY_MEDIA_PREV_TRACK = 0xB1,
  WINDOWS_KEY_MEDIA_STOP = 0xB2,
  WINDOWS_KEY_MEDIA_PLAY_PAUSE = 0xB3,
  WINDOWS_KEY_LAUNCH_MAIL = 0xB4,
  WINDOWS_KEY_LAUNCH_MEDIA_SELECT = 0xB5,
  WINDOWS_KEY_LAUNCH_APP1 = 0xB6,
  WINDOWS_KEY_LAUNCH_APP2 = 0xB7,

  // Misc
  WINDOWS_KEY_OEM_1 = 0xBA,       // ';:' key
  WINDOWS_KEY_OEM_PLUS = 0xBB,    // '+' key
  WINDOWS_KEY_OEM_COMMA = 0xBC,   // ',' key
  WINDOWS_KEY_OEM_MINUS = 0xBD,   // '-' key
  WINDOWS_KEY_OEM_PERIOD = 0xBE,  // '.' key
  WINDOWS_KEY_OEM_2 = 0xBF,       // '/?' key
  WINDOWS_KEY_OEM_3 = 0xC0,       // '`~' key
  WINDOWS_KEY_OEM_4 = 0xDB,       // '[{' key
  WINDOWS_KEY_OEM_5 = 0xDC,       // '\|' key
  WINDOWS_KEY_OEM_6 = 0xDD,       // ']}' key
  WINDOWS_KEY_OEM_7 = 0xDE,       // ''"' key
  WINDOWS_KEY_OEM_8 = 0xDF,       // varies by keyboard

  WINDOWS_KEY_UNKNOWN = 0x00
};